### ISSUE TITLE
[18-3. kor_bert_nsmc_tpu] TPU 모델 저장

### ISSUE THREAD

**Issue by roachmaster555** [ukairia777/tensorflow-nlp-tutorial#2]
안녕하세요!
작가님 덕분에 너무 유용하게 자료들 참고하며 학수하고 있습니다.
질문이 하나 있는데요.

18-3. kor_bert_nsmc_tpu
class TFBertForSequenceClassification(tf.keras.Model) 로 정의하여 학습시킨

model = TFBertForSequenceClassification("klue/bert-base")
model.fit(train_X, train_y, epochs=2, batch_size=64, validation_split=0.2)
results = model.evaluate(test_X, test_y, batch_size=1024)
의 'model'을 colab에서 google drive 내에 저장하는 방법을 여쭤봐도 될까요?

감사합니다! :)

**Comment by roachmaster555** [comment]
현재까지 제가 시도해봤던 스니펫은 다음과 같습니다. (둘 다 안됨)

1.
SAVE
`saved_model_path = './drive/MyDrive/savedModel/model'`
`save_options = tf.saved_model.SaveOptions(experimental_io_device='/job:localhost')`
`model.save(saved_model_path, options=save_options)`

LOAD
`load_options = tf.saved_model.LoadOptions(experimental_io_device='/job:localhost')`
`loaded = tf.keras.models.load_model(saved_model_path, options=load_options)`

문제점
불러온 모델을 지정한 loaded가 저장했던 model과 형식이 다름.



2.
LOAD
`loaded =  TFBertModel.from_pretrained(loaded, from_pt=True)`
문제점
OSError: <tensorflow.python.saved_model.load.Loader._recreate_base_user_object.<locals>._UserObject object at 0x7f42ecc5c850> is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login` and pass `use_auth_token=True`.

**Comment by ukairia777** [comment]
TPU 모델은 저장에 여러 애로 사항이 많아서 저장하시려면 GPU 사용을 권장해드리겠습니다.
