### ISSUE TITLE
pip install glove_python_binary  install 실패 

### ISSUE THREAD

**Issue by lookinsight** [ukairia777/tensorflow-nlp-tutorial#5]
glove 모듀을 사용하기 위해 라이브러리 설치 및 임포트 하려고 했는데,

pip install glove_python_binary 이 코드로 해도 실패하고,

pip install glove_python  만 입력해도 실패합니다.

혹시 해당 라이브러리를 설치하고 임포트 할 수 있는 방법이 있을까요?

**Comment by ukairia777** [comment]
Colab에서 실행한 결과

https://colab.research.google.com/drive/1RjU1q6omX_Z-b3lfymuqus03x6IPBYj0?usp=sharing

정상 동작하는 것을 확인했습니다.

어떤 환경인지, 어떻게 실패하는 건지를 말씀해주시지 않으면 해결이 어렵습니다.

**Comment by ukairia777** [comment]
오래된 이슈라 close 했습니다.
