### ISSUE TITLE
requirements & yaml

### ISSUE THREAD

**Issue by sam351** [ukairia777/tensorflow-nlp-tutorial#6]
안녕하십니까, 좋은 자료 공유 감사드립니다.

본 repo에 환경정보가 따로 정리되어 있지 않고, e-book에도 일부 패키지 정보만 공개되어 있는 것으로 보입니다
혹시 전체 코드 실행이 되는 환경의 requirements 및 yaml 정보도 commit해주실 수 있을까 싶어 issue 남깁니다

감사합니다

**Comment by ukairia777** [comment]
requirements를 별도로 제공해드리진 않고 있습니다. 그 이유는 현재 주기적으로 Colab에서 전체 코드가 동작하는지 확인하고 있는데, Colab이 계속 라이브러리 버전 업이 되니까 이에 따라서 코드를 계속 최신화를 유지하기 위함입니다.
